codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "80...100"

  status:
    project:
      default:
        enabled: yes
        target: 85
        threshold: null
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        enabled: no

ignore:
  - "tests/**"
  - "**/*.ipynb"
